{{- if .Values.anonymousResults.seaweedfs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polars.seaweedfs.fullname" . }}
type: Opaque
stringData:
  aws_access_key_id: {{ randAlpha 20 }}
  aws_secret_access_key: {{ randAlphaNum 40 }}
{{- end }}