---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-report
  labels:
    {{- include "license-server.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOncePod
{{- with .Values.report.storageClass }}
  storageClassName: {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.report.size }}
