---
{{- if .Values.license.content }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.secretName }}
  labels:
    {{- include "license-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.license.key }}: {{ .Values.license.content | b64enc }}
{{- end }}
---
{{- if .Values.tlsBundle.content }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tlsBundle.secretName }}
  labels:
    {{- include "license-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.tlsBundle.key }}: {{ .Values.tlsBundle.content | b64enc }}
{{- end }}