---
{{- if .Values.licenseContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.secretName }}
  labels:
    {{- include "license-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.license.key }}: {{ .Values.licenseContent | b64enc }}
{{- end }}
---
{{- if .Values.bundleContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tlsBundle.secretName }}
  labels:
    {{- include "license-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.tlsBundle.key }}: {{ .Values.bundleContent | b64enc }}
{{- end }}
