apiVersion: v1
kind: Service
metadata:
  name: {{ include "license-server.fullname" . }}
  labels:
    {{- include "license-server.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "license-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: grpc
    - name: http
      port: {{ .Values.service.httpPort }}
      protocol: TCP
      targetPort: http
