{{- if and .Values.shuffleData.sharedPersistentVolumeClaim.enabled .Values.shuffleData.sharedPersistentVolumeClaim.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "polars.shuffleDataPvcName" . }}
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: {{ .Values.shuffleData.sharedPersistentVolumeClaim.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.shuffleData.sharedPersistentVolumeClaim.size }}
{{- end }}
