{{- if .Values.licenseData.enabled }}
  {{- if .Values.licenseData.create }}
    {{- if .Values.licenseData.existingClaimName }}
      {{ fail ".Values.licenseData.create .Values.licenseData.existingClaimName are mutually exclusive"}}
    {{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "polars.licenseCertificatePvcName" . }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.licenseData.storageClassName }}
  resources:
    requests:
      storage: 1Mi
  {{- end }}
{{- end }}
