name: Verify Helm documentation

on:
  - pull_request

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # ratchet:actions/checkout@v5

      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # ratchet:azure/setup-helm@v4.3.1

      - name: Install helm-docs
        uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # ratchet:jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: norwoodj/helm-docs

      - name: Run make docs
        run: |
          make docs
        shell: bash

      - name: Files changed
        run: |
          git diff --exit-code
        shell: bash
